### ISSUE TITLE
admin cp -> attachments -> attachment permissions-> gif -> deny all

### ISSUE THREAD

**Issue by jxsl13** [oneall/social-login-vbulletin#1]
Causes this:
Strict standards: Non-static method OneAllSocialLogin_Toolbox::display_plugin() should not be called statically in .../packages/oneallsociallogin/api/template.php on line 44

**Comment by jxsl13** [comment]
hm new installation and still got the problem, seems to be caused by oneall addon :/

**Comment by SchlesserClaude** [comment]
Hello,

thank you for the bug report, I have added a bugfix here:
https://github.com/oneall/social-login-vbulletin/commit/9d6538b4513218cca86f778c915d2b610fdf400a

**Comment by SchlesserClaude** [comment]
The bug is also fixed in the plugin downloadeable from our documentation : https://docs.oneall.com/plugins/guide/social-login-vbulletin/5/
