### ISSUE TITLE
Documentation link in description

### ISSUE THREAD

**Issue by mtricht** [oneall/social-login-vbulletin#2]
The documentation link in the github repo description is wrong.

In the description:
`http://docs.oneall.loc/plugins/guide/social-login-vbulletin/`

The correct one in the readme:
`https://docs.oneall.com/plugins/guide/social-login-vbulletin/`

(.com vs .loc)

**Comment by SchlesserClaude** [comment]
The .loc is in fact our test server ;) I have fixed the error! Thank you!
