### ISSUE TITLE
Vbulletin 5.3.4

### ISSUE THREAD

**Issue by hanm13** [oneall/social-login-vbulletin#4]
Its does not working for 5.3.4 nor the verify API settings and Autodetect connection settings.

**Comment by zaradamien** [comment]
Hi @hanm13 ,

I just tried on 5.3.4 with 5.0+ Social Login plugin, and both **Verify API Settings** and **Autodetect Connection Settings** are working for me. Could you please reinstall the plugin and retry ? 
Here is a link to download it directly : https://github.com/oneall/social-login-vbulletin/raw/vbulletin/5.0%2B/vbulletin-5.0----oneall_social_login.zip

Thank you.
Damien

**Comment by hanm13** [comment]
I have tried to reinstall it and nothing changed..
I do not see the option for login by any social network I had before.

The auto detection is still not working in my forum.
